version: '3.8'
services:
  backend:
    image: myapp-backend:latest
    ports:
      - "3000:3000"

  frontend:
    image: myapp-frontend:latest
    ports:
      - "5000:80"
  database:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: